---
version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app-network
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    command: npm start

  mongo:
    image: mongo:7.0.14
    networks:
      - app-network
    environment:
      - HOST=mongo
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
